# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Support of a multinomial distribution
#'
#' @param k The number of categories.
#' @param n The sample size.
#'
#' @return
#' @export
#'
#' @examples
multinomial_support <- function(k, n) {
    .Call(`_sharkbox_multinomial_support`, k, n)
}

